baseURL = "https://xsleaks.dev/"
languageCode = "en-us"
title = "Ricardo Chin"
enableGitInfo = false
theme = "hugobook"

[params]
  BookRepo = 'https://github.com/roaked/roaked.github.io'
  BookDateFormat = 'January 2, 2006'
  BookEditPath = 'edit/main/content'
  BookServiceWorker = true
  BookTheme = 'dark'

[author]
  name = "Ricardo Chin"
  email = "ricardo.chin@tecnico.ulisboa.pt"
  github = "roaked"

