baseURL = "https://xsleaks.dev/"
languageCode = "en-us"
title = "Ricardo Chin"
enableGitInfo = true
theme = "hugobook"

[services.googleAnalytics]
  ID = "G-10WQY47KS2"

[params]
  BookRepo = 'https://github.com/roaked/roaked.github.io'
  BookDateFormat = 'January 2, 2006'
  BookEditPath = 'edit/main/content'
  BookServiceWorker = true
  BookSearch = false
  
[author]
  name = "Ricardo Chin"
  email = "ricardo.chin@tecnico.ulisboa.pt"
  github = "roaked"



